In [1]:
import numpy as np
b = np.random.randint(100, 200, (8,))

In [2]:
b

array([115, 108, 151, 171, 190, 111, 118, 123])

In [3]:
np.random.choice(b, (3,2))

array([[171, 118],
       [171, 151],
       [171, 123]])

In [4]:
np.random.choice(b, (3,2), replace=False)

array([[118, 123],
       [108, 115],
       [171, 111]])

In [10]:
np.random.choice(b, (3,2), p = b/np.sum(b))

array([[118, 111],
       [151, 123],
       [190, 190]])

In [11]:
u = np.random.uniform(0, 10, (3,4))

In [12]:
u

array([[5.59463698, 7.2194291 , 2.43415625, 8.81143645],
       [4.23730192, 5.40919958, 7.66749859, 2.06258271],
       [5.38644868, 3.1272949 , 1.09545192, 9.81414039]])

In [13]:
n = np.random.normal(10, 5, (3,4))

In [14]:
n

array([[15.09520783, 11.02032444, 13.73327125, 11.27613472],
       [ 9.09147778, 15.77521082,  5.65701121,  9.77112359],
       [17.14328788, 16.82398448,  8.36110272, 15.61338054]])