In [1]:
import tensorflow as tf
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

: 

: 

In [ ]:
# 创建张量
tf.constant([[1.,2.,3.],[4.,5.,6.]])

In [1]:
tf.constant(42)

NameError: name 'tf' is not defined

In [ ]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])
t.shape

TensorShape([2, 3])

In [ ]:
t.numpy().dtype

dtype('float32')

In [ ]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [ ]:
# 只取出一列
t[..., 1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [ ]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [ ]:
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [ ]:
tf.square(t)

NameError: name 'tf' is not defined

In [ ]:
# 乘以自己的转置
t @ tf.transpose(t)

NameError: name 't' is not defined

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
tf.constant(a)

NameError: name 'tf' is not defined