In [10]:
#ndarray
import numpy as np
a = np.array([[0,1,2,3,4],
             [9,8,7,6,5]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

[[0 1 2 3 4]
 [9 8 7 6 5]]
2
(2, 5)
10
int64
8


In [23]:
np.zeros((3,6), dtype=np.int32)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
x = np.ones((2,3,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [29]:
a = np.arange(1,21,1).reshape(5,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [31]:
b = a[[1,3]]
print(b)

[[ 5  6  7  8]
 [13 14 15 16]]


In [37]:
c = np.full_like(b,2)
print(c)

[[2 2 2 2]
 [2 2 2 2]]


In [38]:
a = np.linspace(1, 10, 4)
print(a)

[ 1.  4.  7. 10.]


In [40]:
b = np.linspace(1, 10, 4, endpoint=False)
print(b)

[1.   3.25 5.5  7.75]


In [42]:
c = np.concatenate((a, b))
print(c)

[ 1.    4.    7.   10.    1.    3.25  5.5   7.75]


In [46]:
c = c.reshape(2,4)
print(c)

[[ 1.    4.    7.   10.  ]
 [ 1.    3.25  5.5   7.75]]


In [47]:
d = c.flatten()
print(d)

[ 1.    4.    7.   10.    1.    3.25  5.5   7.75]
