In [2]:
#ndarray
import numpy as np
a = np.array([[0,1,2,3,4],
             [9,8,7,6,5]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

[[0 1 2 3 4]
 [9 8 7 6 5]]
2
(2, 5)
10
int64
8


In [23]:
np.zeros((3,6), dtype=np.int32)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
x = np.ones((2,3,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [29]:
a = np.arange(1,21,1).reshape(5,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [31]:
b = a[[1,3]]
print(b)

[[ 5  6  7  8]
 [13 14 15 16]]


In [37]:
c = np.full_like(b,2)
print(c)

[[2 2 2 2]
 [2 2 2 2]]


In [38]:
a = np.linspace(1, 10, 4)
print(a)

[ 1.  4.  7. 10.]


In [40]:
b = np.linspace(1, 10, 4, endpoint=False)
print(b)

[1.   3.25 5.5  7.75]


In [42]:
c = np.concatenate((a, b))
print(c)

[ 1.    4.    7.   10.    1.    3.25  5.5   7.75]


In [46]:
c = c.reshape(2,4)
print(c)

[[ 1.    4.    7.   10.  ]
 [ 1.    3.25  5.5   7.75]]


In [47]:
d = c.flatten()
print(d)

[ 1.    4.    7.   10.    1.    3.25  5.5   7.75]


In [12]:
a = np.arange(24).reshape((2,3,4))
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
print(a[-1, -2, -3])

17


In [13]:
a[:, 1, -3]

array([ 5, 17])

In [14]:
a[:,:,::2]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

In [15]:
#取算数平均值
a.mean()

11.5

In [17]:
a = a/a.mean()
print(a)

[[[0.         0.08695652 0.17391304 0.26086957]
  [0.34782609 0.43478261 0.52173913 0.60869565]
  [0.69565217 0.7826087  0.86956522 0.95652174]]

 [[1.04347826 1.13043478 1.2173913  1.30434783]
  [1.39130435 1.47826087 1.56521739 1.65217391]
  [1.73913043 1.82608696 1.91304348 2.        ]]]


In [21]:
np.modf(a)

(array([[[0.        , 0.08695652, 0.17391304, 0.26086957],
         [0.34782609, 0.43478261, 0.52173913, 0.60869565],
         [0.69565217, 0.7826087 , 0.86956522, 0.95652174]],
 
        [[0.04347826, 0.13043478, 0.2173913 , 0.30434783],
         [0.39130435, 0.47826087, 0.56521739, 0.65217391],
         [0.73913043, 0.82608696, 0.91304348, 0.        ]]]),
 array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 2.]]]))

In [22]:
np.exp(a)

array([[[1.        , 1.09084925, 1.18995209, 1.29805834],
        [1.41598597, 1.54462723, 1.68495546, 1.8380324 ],
        [2.00501627, 2.18717049, 2.38587329, 2.60262809]],

       [[2.8390749 , 3.09700273, 3.37836311, 3.68528486],
        [4.02009023, 4.38531241, 4.78371476, 5.21831166],
        [5.69239136, 6.20954085, 6.77367299, 7.3890561 ]]])

In [32]:
a = np.arange(24).reshape((2,3,4))

In [33]:
np.square(a)

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]])

In [34]:
np.sqrt(a)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131],
        [2.82842712, 3.        , 3.16227766, 3.31662479]],

       [[3.46410162, 3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069, 4.35889894],
        [4.47213595, 4.58257569, 4.69041576, 4.79583152]]])

In [37]:
a = np.arange(100).reshape(5, 20)
np.savetxt('a.csv', a, fmt = '%2d', delimiter=',')

In [39]:
b = np.loadtxt('a.csv',delimiter=',')
print(b)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37.
  38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53. 54. 55. 56. 57.
  58. 59.]
 [60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71. 72. 73. 74. 75. 76. 77.
  78. 79.]
 [80. 81. 82. 83. 84. 85. 86. 87. 88. 89. 90. 91. 92. 93. 94. 95. 96. 97.
  98. 99.]]


In [ ]:
a = np.arange(100).reshape(5,10,2)
a.tofile("b.bat", sep=',', format='%d')