In [1]:
import numpy as np
b = np.random.randint(100, 200, (8,))

In [2]:
b

array([115, 108, 151, 171, 190, 111, 118, 123])

In [3]:
np.random.choice(b, (3,2))

array([[171, 118],
       [171, 151],
       [171, 123]])

In [4]:
np.random.choice(b, (3,2), replace=False)

array([[118, 123],
       [108, 115],
       [171, 111]])

In [10]:
np.random.choice(b, (3,2), p = b/np.sum(b))

array([[118, 111],
       [151, 123],
       [190, 190]])

In [11]:
u = np.random.uniform(0, 10, (3,4))

In [12]:
u

array([[5.59463698, 7.2194291 , 2.43415625, 8.81143645],
       [4.23730192, 5.40919958, 7.66749859, 2.06258271],
       [5.38644868, 3.1272949 , 1.09545192, 9.81414039]])

In [13]:
n = np.random.normal(10, 5, (3,4))

In [14]:
n

array([[15.09520783, 11.02032444, 13.73327125, 11.27613472],
       [ 9.09147778, 15.77521082,  5.65701121,  9.77112359],
       [17.14328788, 16.82398448,  8.36110272, 15.61338054]])

In [2]:
import numpy as np 
a = np.arange(15).reshape(3,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
np.sum(a)

105

In [7]:
np.mean(a, axis=1)

array([ 2.,  7., 12.])

In [9]:
np.average(a, axis=0, weights=[10, 5, 1])

array([2.1875, 3.1875, 4.1875, 5.1875, 6.1875])

In [11]:
#标准差
np.std(a)

4.320493798938574

In [12]:
#方差
np.var(a)

18.666666666666668

In [14]:
b = np.arange(15, 0, -1).reshape(3, 5)
b

array([[15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [17]:
np.ptp(b)

14

In [22]:
np.argmin(b)

14

In [29]:
np.unravel_index(np.argmax(b), b.shape)

(0, 0)

In [30]:
np.median(b)

8.0

In [31]:
a = np.random.randint(0, 20, (5))
a

array([17,  6,  3, 12,  1])

In [32]:
np.gradient(a)

array([-11.,  -7.,   3.,  -1., -11.])

In [34]:
b = np.random.randint(0, 20, (5))
b

array([ 1,  9,  7, 19, 12])

In [35]:
np.gradient(b)

array([ 8. ,  3. ,  5. ,  2.5, -7. ])

In [37]:
c = np.random.randint(0, 50, (3, 5))
c

array([[13, 37, 47, 47, 22],
       [11, 24,  7, 24,  5],
       [21, 45, 33,  0,  7]])

In [38]:
np.gradient(c)

[array([[ -2. , -13. , -40. , -23. , -17. ],
        [  4. ,   4. ,  -7. , -23.5,  -7.5],
        [ 10. ,  21. ,  26. , -24. ,   2. ]]),
 array([[ 24. ,  17. ,   5. , -12.5, -25. ],
        [ 13. ,  -2. ,   0. ,  -1. , -19. ],
        [ 24. ,   6. , -22.5, -13. ,   7. ]])]