In [42]:
#ndarray
import numpy as np
a = np.array([[0,1,2,3,4],
             [9,8,7,6,5]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

[[0 1 2 3 4]
 [9 8 7 6 5]]
2
(2, 5)
10
int32
4


In [43]:
np.zeros((3,6), dtype=np.int32)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
x = np.ones((2,3,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [46]:
a = np.arange(1,21,1).reshape(5,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [47]:
b = a[[1,3]]
print(b)

[[ 5  6  7  8]
 [13 14 15 16]]


In [48]:
c = np.full_like(b,2)
print(c)

[[2 2 2 2]
 [2 2 2 2]]


In [49]:
a = np.linspace(1, 10, 4)
print(a)

[ 1.  4.  7. 10.]


In [50]:
b = np.linspace(1, 10, 4, endpoint=False)
print(b)

[1.   3.25 5.5  7.75]


In [51]:
c = np.concatenate((a, b))
print(c)

[ 1.    4.    7.   10.    1.    3.25  5.5   7.75]


In [52]:
c = c.reshape(2,4)
print(c)

[[ 1.    4.    7.   10.  ]
 [ 1.    3.25  5.5   7.75]]


In [53]:
d = c.flatten()
print(d)

[ 1.    4.    7.   10.    1.    3.25  5.5   7.75]


In [54]:
sn = np.random.rand(3, 4, 5)

In [55]:
sn

array([[[0.88393648, 0.32551164, 0.1650159 , 0.39252924, 0.09346037],
        [0.82110566, 0.15115202, 0.38411445, 0.94426071, 0.98762547],
        [0.45630455, 0.82612284, 0.25137413, 0.59737165, 0.90283176],
        [0.53455795, 0.59020136, 0.03928177, 0.35718176, 0.07961309]],

       [[0.30545992, 0.33071931, 0.7738303 , 0.03995921, 0.42949218],
        [0.31492687, 0.63649114, 0.34634715, 0.04309736, 0.87991517],
        [0.76324059, 0.87809664, 0.41750914, 0.60557756, 0.51346663],
        [0.59783665, 0.26221566, 0.30087131, 0.02539978, 0.30306256]],

       [[0.24207588, 0.55757819, 0.56550702, 0.47513225, 0.29279798],
        [0.06425106, 0.97881915, 0.33970784, 0.49504863, 0.97708073],
        [0.44077382, 0.31827281, 0.51979699, 0.57813643, 0.85393375],
        [0.06809727, 0.46453081, 0.78194912, 0.71860281, 0.58602198]]])

In [56]:
b = np.random.randint(100, 200, (3, 4))

In [57]:
b

array([[130, 189, 125, 178],
       [181, 185, 162, 113],
       [141, 133, 104, 187]])

In [58]:
np.random.seed(10)

In [59]:
np.random.randint(100, 200, (3, 4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [60]:
np.random.seed(10)

In [61]:
np.random.randint(100, 200, (3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [62]:
np.random.randint(100, 200, (3, 4))

array([[116, 111, 154, 188],
       [162, 133, 172, 178],
       [149, 151, 154, 177]])

In [63]:
np.random.shuffle(a)

In [64]:
a

array([ 1.,  7., 10.,  4.])

In [65]:
np.random.shuffle(a)

In [66]:
a

array([ 1.,  4., 10.,  7.])

In [67]:
np.random.randint(100, 200, (3, 4))

array([[192, 186, 130, 130],
       [189, 112, 165, 131],
       [157, 136, 127, 118]])

In [68]:
np.random.permutation(a)

array([10.,  1.,  7.,  4.])

In [69]:
a

array([ 1.,  4., 10.,  7.])